##############################
# INCLUDED ITEMS BY BOARD ID #
##############################

### GET ALL CARDS BY BOARD ID
GET http://localhost:3000/boards/1/cards
### ERROR CHECK
GET http://localhost:3000/boards/420/cards


### CREATE NEW CARD BY BOARD ID
POST http://localhost:3000/boards/1/cards
Content-Type: application/json
Accept: application/json

{
  "title": "Nouvelle carte"
}
### ERROR CHECK
POST http://localhost:3000/boards/420/cards
Content-Type: application/json
Accept: application/json

{
  "FEF": "Loisirs",
}
### DELETE ALL CARDS BY BOARD ID
DELETE http://localhost:3000/boards/1/cards
### ERROR CHECK
DELETE http://localhost:3000/boards/420/cards


### GET ONE CARD BY BOARD ID
GET http://localhost:3000/boards/2/cards/1
### ERROR CHECK
GET http://localhost:3000/boards/2/cards/420


### GET ALL TODOS BY CARD ID
GET http://localhost:3000/boards/1/cards/1/todos
### ERROR CHECK
GET http://localhost:3000/boards/1/cards/420/todos

### UPDATE TODO BY CARD AND TODO ID
PATCH http://localhost:3000/boards/1/cards/6/todos/26
Content-Type: application/json

{
  "title": "Updated Card yayy"
}


### DELETE ALL TODOS BY CARD ID
DELETE http://localhost:3000/boards/1/cards/1/todos
### ERROR CHECK
DELETE http://localhost:3000/boards/1/cards/420/todos


### ASSOCIATE TODO ID WITH TAG IG
POST http://localhost:3000/boards/1/cards/1/todos/1/tag HTTP/1.1
Content-Type: application/json

{
  "name": "Loisirs",
}
### URL ENCODED
POST http://localhost:3000/boards/1/cards/1/todos/1/tag
Content-Type: application/x-www-form-urlencoded

name=Loisirs

### ERROR CHECK
POST http://localhost:3000/boards/1/cards/1/todos/1/tag
Content-Type: application/x-www-form-urlencoded

name=qhfiuehfquhfnd


### DELETE TODO AND TAG ASSOCIATION
DELETE http://localhost:3000/boards/1/cards/1/todos/1/tag/5
### ERROR CHECK
DELETE http://localhost:3000/boards/1/cards/1/todos/420/tag/240



##############################
#           BOARDS           #
##############################

### GET ALL BOARDS
GET http://localhost:3000/boards


### GET ONE BOARD BY ID
GET http://localhost:3000/boards/2
### ERROR CHECK 
GET http://localhost:3000/boards/420


### CREATE NEW BOARD
POST http://localhost:3000/boards
Content-Type: application/json

{
  "title": "New Board Test",
  "description": "This is my test board yo!"
}
### URL ENCODED
POST http://localhost:3000/boards
Content-Type: application/x-www-form-urlencoded

title=Test&description=This is my test board yo!

### ERROR CHECK
POST http://localhost:3000/boards
Content-Type: application/x-www-form-urlencoded

tilot=Test&description=This is my test board yo!&member_id=1


### UPDATE BOARD BY ID
PATCH http://localhost:3000/boards/6
Content-Type: application/json

{
  "title": "Updated Board !"
}
### URL ENCODED
PATCH http://localhost:3000/boards/6
Content-Type: application/x-www-form-urlencoded

title=New Title&description=Because I'm edited yo

### ERROR CHECK
PATCH http://localhost:3000/boards/420
Content-Type: application/x-www-form-urlencoded

asperge=New veg&description=okgoogle


### DELETE BOARD BY ID
DELETE http://localhost:3000/boards/6
### ERROR CHECK
DELETE http://localhost:3000/boards/420


### DELETE ALL BOARDS
DELETE http://localhost:3000/boards



##############################
#           CARDS            #
##############################

### GET ALL CARDS
GET http://localhost:3000/cards

### GET ONE CARD BY ID
GET http://localhost:3000/cards/2
### ERROR CHECK
GET http://localhost:3000/cards/420


### CREATE NEW CARD
POST http://localhost:3000/cards
Content-Type: application/json

{
  "title": "New Card Test",
}
### URL ENCODED 
POST http://localhost:3000/cards
Content-Type: application/x-www-form-urlencoded

title=New Test Card

### ERROR CHECK
POST http://localhost:3000/cards
Content-Type: application/x-www-form-urlencoded

tile=New Test Card


### UPDATE CARD
PATCH http://localhost:3000/cards/6
Content-Type: application/json

{
  "position": 2
}
### URL ENCODED
PATCH http://localhost:3000/cards/6
Content-Type: application/x-www-form-urlencoded

position=6

### ERROR CHECK
PATCH http://localhost:3000/cards/420
Content-Type: application/x-www-form-urlencoded

tile=New Title&kription=Because I'm edited yo


### DELETE CARD BY ID
DELETE http://localhost:3000/cards/6
### ERROR CHECK
DELETE http://localhost:3000/cards/420


### DELETE ALL CARDS
DELETE http://localhost:3000/cards



##############################
#           TODOS            #
##############################

### GET ALL TODOS
GET http://localhost:3000/todos


### GET ONE TODO
GET http://localhost:3000/todos/2
### ERROR CHECK
GET http://localhost:3000/todos/420


### CREATE NEW TODO
POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": "New Todo Test",
  "position": 10,
  "color": "new color",
  "card_id": 1
}
### URL ENCODED 
POST http://localhost:3000/todos
Content-Type: application/x-www-form-urlencoded

title=New Todo Test&position=10&color=new color&card_id=1

### ERROR CHECK
POST http://localhost:3000/todos
Content-Type: application/x-www-form-urlencoded

tile=New Todo Test&position=10&color=new color&card_id=1


### UPDATE TODO
PATCH http://localhost:3000/todos/15
Content-Type: application/json

{
  "title": "Updated Todo !"
}
### URL ENCODED
PATCH http://localhost:3000/todos/15
Content-Type: application/x-www-form-urlencoded

title=Updated Todo !

### ERROR CHECK
PATCH http://localhost:3000/todos/420
Content-Type: application/x-www-form-urlencoded

title=Updated Todo !


### DELETE TODO
DELETE http://localhost:3000/todos/15
### ERROR CHECK
DELETE http://localhost:3000/todos/420



##############################
#           TAGS            #
##############################

### GET ALL TAGS
GET http://localhost:3000/tags


### GET ONE TAG
GET http://localhost:3000/tags/6
### ERROR CHECK
GET http://localhost:3000/tags/420


### CREATE NEW TAG
POST http://localhost:3000/tags
Content-Type: application/json

{
  "name": "New Test Tag",
  "position": 5,
  "color": "colored"
}
### URL ENCODED 
POST http://localhost:3000/tags
Content-Type: application/x-www-form-urlencoded

name=New Test Tag&position=5&color=colored

### ERROR CHECK
POST http://localhost:3000/tags
Content-Type: application/x-www-form-urlencoded

nom=New Test Tag&position=5&color=colored


### UPDATE TAG
PATCH http://localhost:3000/tags/6
Content-Type: application/json

{
  "name": "Updated Tag !"
}
### URL ENCODED
PATCH http://localhost:3000/tags/6
Content-Type: application/x-www-form-urlencoded

name=Updated Tag !

### ERROR CHECK
PATCH http://localhost:3000/tags/420
Content-Type: application/x-www-form-urlencoded

name=Updated Tag !


### DELETE TAG
DELETE http://localhost:3000/tags/6
### ERROR CHECK
DELETE http://localhost:3000/tags/420


### DELETE ALL TAGS
DELETE http://localhost:3000/tags