
BEGIN; 

DROP TABLE IF EXISTS "member",
"board",
"card",
"todo",
"tag",
"todo_has_tag";

-- -----------------------------------------------------
-- Table "member"
-- -----------------------------------------------------
CREATE TABLE "member" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'member',
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "board"
-- -----------------------------------------------------
CREATE TABLE "board" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" TEXT NOT NULL,
  "description" TEXT NULL,
  "member_id" INTEGER NOT NULL REFERENCES "member"("id") ON DELETE CASCADE,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "card"
-- -----------------------------------------------------
CREATE TABLE "card" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" TEXT NOT NULL,
  "position" INTEGER NOT NULL,
  "board_id" INTEGER NOT NULL REFERENCES "board"("id") ON DELETE CASCADE,
  "hidden" TEXT NOT NULL DEFAULT 'FALSE',
  "color" TEXT NOT NULL DEFAULT 'default',
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "todo"
-- -----------------------------------------------------
CREATE TABLE "todo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" TEXT NOT NULL,
  "position" INTEGER NOT NULL,
  "card_id" INTEGER NOT NULL REFERENCES "card"("id") ON DELETE CASCADE,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "tag"
-- -----------------------------------------------------
CREATE TABLE "tag" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "color" TEXT NOT NULL DEFAULT '#FFF',
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "todo_has_tag"
-- -----------------------------------------------------
CREATE TABLE "todo_has_tag" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "todo_id" INTEGER NOT NULL REFERENCES "todo"("id") ON DELETE CASCADE,
  "tag_id" INTEGER NOT NULL REFERENCES "tag"("id") ON DELETE CASCADE,
  "created_at" timestamptz NOT NULL DEFAULT NOW()
);


COMMIT;
BEGIN;

INSERT INTO "member" ("id", "email", "password", "role") VALUES (1, 'admin@admin.io', 'salut', 'admin');
INSERT INTO "board" ("id", "title", "description", "member_id") VALUES (1, 'Perso', 'J''ai faim !!', 1);
INSERT INTO "card" ("id", "title", "position", "board_id") VALUES (1, 'Liste des courses', 0, 1);
INSERT INTO "todo" ("id", "title", "position", "card_id") VALUES (1, '5 pommes', 0, 1), (2, '1kg de PDT', 1, 1), (3, '3 Melons', 2, 1), (4, 'Pain', 3, 1), (5, 'Pack d''Iced Tea', 4, 1);
INSERT INTO "tag" ("id", "name") VALUES (1, 'Urgent'), (2, 'Caprice'), (3, 'Cadeau');
INSERT INTO "todo_has_tag" ("todo_id", "tag_id") VALUES (5, 1), (4, 2) ,(3, 3), (3, 2);

COMMIT;
BEGIN;

SELECT setval('member_id_seq', (SELECT MAX(id) from "member"));
SELECT setval('board_id_seq', (SELECT MAX(id) from "board"));
SELECT setval('card_id_seq', (SELECT MAX(id) from "card"));
SELECT setval('todo_id_seq', (SELECT MAX(id) from "todo"));
SELECT setval('tag_id_seq', (SELECT MAX(id) from "tag"));

COMMIT;