
BEGIN; 

DROP TABLE IF EXISTS "member",
"board",
"card",
"todo",
"tag";

-- -----------------------------------------------------
-- Table "member"
-- -----------------------------------------------------
CREATE TABLE "member" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "email" text NOT NULL,
  "password" text NOT NULL,
  "role" text DEFAULT 'member'
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "board"
-- -----------------------------------------------------
CREATE TABLE "board" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "description" text NULL
  "member_id" integer NOT NULL REFERENCES "member"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "card"
-- -----------------------------------------------------
CREATE TABLE "card" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "position" integer NULL,
  "board_id" integer NOT NULL REFERENCES "board"("id"),
  "hidden" boolean NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "todo"
-- -----------------------------------------------------
CREATE TABLE "todo" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "position" text NOT NULL,
  "color" integer NULL,
  "card_id" integer NOT NULL REFERENCES "card"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "tag"
-- -----------------------------------------------------
CREATE TABLE "tag" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "color" integer NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "tag"
-- -----------------------------------------------------
CREATE TABLE "todo_has_tag" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "todo_id" integer NOT NULL REFERENCES "todo"("id"),
  "tag_id" integer NOT NULL REFERENCES "tag"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz,
  UNIQUE ("todo_id", "tag_id")
);


COMMIT;
BEGIN;

INSERT INTO "member" ("id", "email", "password", "role") VALUES (1, 'admin@admin.io', 'salut', 'admin');
INSERT INTO "board" ("id", "title", "description", "member_id") VALUES (1, 'Perso', 'J''ai faim !!', 1);
INSERT INTO "card" ("id", "title", "position", "hidden", "board_id") VALUES (1, 'Liste des courses', 0, "FALSE", 1);
INSERT INTO "todo" ("id", "title", "position", "color", "card_id") VALUES (1, '5 pommes', 0, 1), (2, '1kg de PDT', 1, 1), (3, '3 Melons', 2, 1), (4, 'Pain', 3, 1), (5, 'Pack d''Iced Tea', 4, 1),
INSERT INTO "tag" ("id", "name") VALUES (1, 'Urgent'), (2, 'Caprice'), (3, 'Cadeau');
INSERT INTO "todo_has_tag" ("todo_id", "tag_id") VALUES (5, 1), (4, 2) ,(3, 3), (3, 2);

COMMIT;
BEGIN;

SELECT setval('member_id_seq', (SELECT MAX(id) from "member"));
SELECT setval('board_id_seq', (SELECT MAX(id) from "board"));
SELECT setval('card_id_seq', (SELECT MAX(id) from "card"));
SELECT setval('todo_id_seq', (SELECT MAX(id) from "todo"));
SELECT setval('tag_id_seq', (SELECT MAX(id) from "tag"));

COMMIT;